services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
